### ISSUE TITLE
Implementation of the Goal System - Presentation & Model Layer

### ISSUE THREAD

**Issue by loopedfrog4** [2100711/ICT2106_P1-6#14]
This thread provides updates regarding the Presentation and Model layer of Goal System features.

**Comment by irfaan96** [comment]
Added base classes for the Goal System feature

**Comment by irfaan96** [comment]
Added the API calls for all the CRUD functions
Updated the UI to display all goals and current goal

**Comment by irfaan96** [comment]
Updated the API calls and the implementations inside the controllers that communicates with DB

**Comment by irfaan96** [comment]
Added progress field to the model

**Comment by irfaan96** [comment]
Added "Create Report" button to implement Carbon Footprint Analysis feature to generate report

**Comment by irfaan96** [comment]
Integrated the Goals feature to the Lab level repo

**Comment by irfaan96** [comment]
Refactored the codes to match the new Database Handle implementation

**Comment by irfaan96** [comment]
Implemented Goals Dashboard and Refactored the codes to be implemented on their respective pages
Also incorporated Goal Forecast feature

**Comment by irfaan96** [comment]
Updated the dashboard to add more information like Carbon Emission by Product Category and Predicted consumption
Fixed minor things like closing modal after creating or updating goals
Minor Cosmetic changes

**Comment by irfaan96** [comment]
Further code cleanups and refactoring
