### ISSUE TITLE
Implementation of RewardRepository and IRewardRepository

### ISSUE THREAD

**Issue by 2100711** [2100711/ICT2106_P1-6#44]
This thread provides updates related to RewardRepository and IRewardRepository

**Comment by jibai-kia** [comment]
### **RewardManagement.cs**
```
/// RewardManagement.cs
using CleanBrightCompany.Data;
namespace CleanBrightCompany.Domain
{
  public class RewardManagement : IRewardManagement
  {
    public IEnumerable<Reward> GetAllRewards()
    {
      var rewardGw = DatabaseHandleFactory.GetReadTableHandle<Reward>();
      return rewardGw.GetAll().Cast<Reward>().ToList();
    }

    public Reward GetRewardById(int id)
    {
      var rewardGw = DatabaseHandleFactory.GetReadRowHandle<Reward>();
      return rewardGw.Find(r => r.Id == id);
    }


    public void CreateReward(Reward reward)
    {
      var rewardGw = DatabaseHandleFactory.GetWriteHandle<Reward>();
      rewardGw.Create((Reward)reward);
    }

    public void UpdateReward(Reward reward)
    {
      var rewardGw = DatabaseHandleFactory.GetWriteHandle<Reward>();
      rewardGw.Update((Reward)reward);
    }

    public void DeleteReward(Reward reward)
    {
      var rewardGw = DatabaseHandleFactory.GetWriteHandle<Reward>();
      rewardGw.Delete(reward.GetId());
    }
  }
}

```

**Comment by jibai-kia** [comment]
### **IRewardManagement.cs**
```
// IRewardManagement.cs
namespace CleanBrightCompany.Domain
{
  public interface IRewardManagement
  {
    IEnumerable<Reward> GetAllRewards();

    Reward GetRewardById(int id);

    void CreateReward(Reward reward);

    void UpdateReward(Reward reward);

    void DeleteReward(Reward reward);
  }
}
```

**Comment by jibai-kia** [comment]
### **Explanation**
This is a C# class named "RewardManagement" which belongs to the "CleanBrightCompany.Domain" namespace. It implements the "IRewardManagement" interface and provides CRUD (Create, Read, Update, and Delete) operations for managing rewards.

Here is a summary of the methods provided by this class:

- "GetAllRewards()" method: This method retrieves all rewards from the database and returns them as a list of Reward objects.
- "GetRewardById(int id)" method: This method retrieves a reward from the database based on its ID and returns it as a Reward object.
- "CreateReward(Reward reward)" method: This method creates a new reward in the database based on the given Reward object.
- "UpdateReward(Reward reward)" method: This method updates an existing reward in the database based on the given Reward object.
- "DeleteReward(Reward reward)" method: This method deletes an existing reward from the database based on the given Reward object.

Note that all the methods use the "DatabaseHandleFactory" class to get the appropriate database handles for reading, writing, and deleting data. The Reward class seems to be a model class that defines the properties of a reward.

**Comment by jibai-kia** [comment]
### **Explanation**
This is a C# interface named "IRewardManagement" which belongs to the "CleanBrightCompany.Domain" namespace. It defines the contract for managing rewards and declares the following methods:

- "GetAllRewards()" method: This method retrieves all rewards from the database and returns them as a collection of Reward objects.
- "GetRewardById(int id)" method: This method retrieves a reward from the database based on its ID and returns it as a Reward object.
- "CreateReward(Reward reward)" method: This method creates a new reward in the database based on the given Reward object.
- "UpdateReward(Reward reward)" method: This method updates an existing reward in the database based on the given Reward object.
- "DeleteReward(Reward reward)" method: This method deletes an existing reward from the database based on the given Reward object.

Note that this interface is implemented by the "RewardManagement" class, which provides the actual implementation of these methods. By using an interface, the code can be more flexible and easier to maintain, as different implementations of the interface can be easily swapped without affecting the rest of the code.
