### ISSUE TITLE
Implementation of RewardService and IRewardService

### ISSUE THREAD

**Issue by 2100711** [2100711/ICT2106_P1-6#46]
This thread provides updates related to RewardService and IRewardService

**Comment by jibai-kia** [comment]
### **RewardService.cs**
```
// RewardService.cs
namespace CleanBrightCompany.Domain
{
    public class RewardService : IRewardService
    {
        private readonly IRewardsRepository _repository;

        public RewardService(IRewardsRepository repository)
        {
            _repository = repository;
        }

        public IEnumerable<Reward> GetAllRewards()
        {
            return _repository.GetAllRewards();
        }

        public Reward GetRewardById(int id)
        {
            return _repository.GetRewardById(id);
        }

        public void CreateReward(Reward reward)
        {
            _repository.CreateReward(reward);
        }

        public void UpdateReward(Reward reward)
        {
            _repository.UpdateReward(reward);
        }

        public void DeleteReward(Reward reward)
        {
            _repository.DeleteReward(reward);
        }
    }
}
```

**Comment by jibai-kia** [comment]
### **IRewardService.cs**
```
// IRewardService.cs
namespace CleanBrightCompany.Domain
{
    public interface IRewardService
    {
        IEnumerable<Reward> GetAllRewards();

        Reward GetRewardById(int id);

        void CreateReward(Reward reward);

        void UpdateReward(Reward reward);

        void DeleteReward(Reward reward);
    }
}
```

**Comment by jibai-kia** [comment]
### **Explanation**
It looks like the ```RewardService``` class is implementing the ```IRewardService``` interface and is responsible for handling the business logic related to rewards. It takes an instance of ```IRewardsRepository``` in its constructor, which is used to perform CRUD operations on the database.

The ```GetAllRewards()``` method returns all the rewards from the repository, while ```GetRewardById(int id)``` retrieves a reward based on its unique identifier.

The ```CreateReward(Reward reward)```, ```UpdateReward(Reward reward)```, and ```DeleteReward(Reward reward)``` methods are responsible for creating, updating, and deleting rewards, respectively, in both the repository and the view model.

**Comment by jibai-kia** [comment]
### **Explanation**
The ```IRewardService``` interface defines the contract for a service that provides operations related to rewards. The interface includes methods for retrieving all rewards, retrieving a reward by its ID, creating a new reward, updating an existing reward, and deleting a reward. This interface is used to decouple the business logic of the application from the implementation details of the repository that handles the persistence of reward data. By depending only on this interface, other parts of the application can easily switch out the implementation of the service without affecting the code that consumes it.
