### ISSUE TITLE
Implementation of RewardsController

### ISSUE THREAD

**Issue by 2100711** [2100711/ICT2106_P1-6#47]
This thread provides updates related to RewardsController

**Comment by jibai-kia** [comment]
### **RewardsController.cs**
```
using Microsoft.AspNetCore.Mvc;
using CleanBrightCompany.Domain;
// RewardsController.cs
namespace CleanBrightCompany.Controllers
{
  [ApiController]
  [Route("api/[controller]")]
  public class RewardsController : ControllerBase
  {
    private readonly IRewardManagement _rewardManagement;

    public RewardsController()
    {
      _rewardManagement = new RewardManagement();
    }

    [HttpGet]
    public ActionResult<IEnumerable<Reward>> GetAllRewards()
    {
      var rewards = _rewardManagement.GetAllRewards();
      return Ok(rewards);
    }

    [HttpGet("{id}")]
    public ActionResult<Reward> GetRewardById(int id)
    {
      var reward = _rewardManagement.GetRewardById(id);

      if (reward == null)
      {
        return NotFound();
      }

      return Ok(reward);
    }

    [HttpPost]
    public ActionResult<IEnumerable<Reward>> CreateReward([FromBody] Reward reward)
    {
      if (reward == null)
      {
        return BadRequest();
      }

      try
      {
        _rewardManagement.CreateReward(reward);
        return Ok(reward);
      }
      catch (ArgumentException ex)
      {
        return BadRequest(ex.Message);
      }
    }

    [HttpPut("{id}")]
    public ActionResult<IEnumerable<Reward>> UpdateReward(int id, [FromBody] Reward reward)
    {
      if (reward == null || id != reward.GetId())
      {
        return BadRequest();
      }

      try
      {
        _rewardManagement.UpdateReward(reward);
        return Ok(reward);
      }
      catch (ArgumentException ex)
      {
        return BadRequest(ex.Message);
      }
    }

    [HttpDelete("{id}")]
    public ActionResult DeleteReward(int id)
    {
      try
      {
        var reward = _rewardManagement.GetRewardById(id);
        if (reward == null)
        {
          return NotFound($"Reward with ID {id} not found");
        }

        _rewardManagement.DeleteReward(reward);
        return Ok(reward);
      }
      catch (ArgumentException ex)
      {
        return NotFound(ex.Message);
      }
    }

  }
}
```

**Comment by jibai-kia** [comment]
### **Explanation**
The RewardsController class is a controller for the Reward resource in the API. It defines a set of endpoints that can be accessed to perform CRUD (Create, Read, Update, Delete) operations on rewards.

The controller uses an instance of IRewardManagement to perform the necessary operations on the rewards. The HTTP methods are mapped to specific controller methods using the attributes [HttpGet], [HttpPost], [HttpPut], and [HttpDelete].

- The GetAllRewards method is mapped to an HTTP GET request and returns a list of all rewards.
- The GetRewardById method is mapped to an HTTP GET request that takes an ID parameter and returns a reward with the given ID.
- The CreateReward method is mapped to an HTTP POST request and creates a new reward.
- The UpdateReward method is mapped to an HTTP PUT request that takes an ID parameter and updates a reward with the given ID.
- The DeleteReward method is mapped to an HTTP DELETE request that takes an ID parameter and deletes a reward with the given ID.

Each method returns an instance of the ActionResult class, which encapsulates the HTTP response. The methods can return Ok, BadRequest, NotFound or other HTTP response types.

Overall, the RewardsController defines the API endpoints and delegates the actual implementation of CRUD operations to the RewardManagement class, which in turn uses the RewardsRepository class to interact with the database.
