### ISSUE TITLE
What Went Wrong

### ISSUE THREAD

**Issue by catifier** [2100711/ICT2106_P1-6#53]

**Comment by catifier** [comment]
At the beginning, our lab group did not really have a leader to manage the main Github repository, leading to an integration rush right before the client presentation. Also, there were little communication between the teams, much less the modules, regarding integration. It can likely be attributed to different way of working, but still affected the integration nontheless.

**Comment by hengwej** [comment]
For the second part, I think what was not done well was the confusion of coding on which repository, whether our own team repository or the branched repository that is to be integrated. This caused last minute implementation of codes during integration which caused a lot of issues just before the client meeting. Also, github was down the night before the client meeting which made everyone very anxious not knowing if we are able to complete implementing and integrating the features.

**Comment by irfaan96** [comment]
For D2, I would say that we had slightly better communication with other teams but it was not enough as we were not able to integrate certain components in our features that are from the other modules. We were also coding in our own repository before integrating to the lab repository which caused further setbacks as the implementations on the lab repository was totally different from what we worked on. So we had to relook all the components and try to troubleshoot all the error that are raised.

**Comment by jibai-kia** [comment]
Our team encountered communication and integration issues while working on D2. We had trouble integrating components from other modules into our features and initially coded in our own repository before integrating with the lab repository. This caused setbacks and errors which we had to troubleshoot. There was a lack of leadership in managing the Github repository, and limited communication between teams and modules. Additionally, there was confusion about which repository to code on, causing last-minute implementation and issues before the client meeting. Github downtime also added to the anxiety.
