### ISSUE TITLE
Week 13 March 31 Retrospection

### ISSUE THREAD

**Issue by catifier** [2100711/ICT2106_P1-6#54]

**Comment by catifier** [comment]
There was extensive discussions in class regarding how the teams and modules should integrate together. However, a lot of it proved to be infeasible or difficult, leading to the teams finding alternatives, and ultimately affecting the final integration.

Drop: Long, theoretical discussions.

During implementation, there was a lot of coding, but not much testing was done.

Add: More tests.

Overall, my team was great and there were no conflicts.

Keep: Great team dynamics.

During this sprint, there was a rush to integrate a few days before the final client presentation. In the future, I will definitely try my best to avoid this rush.

Improve: Time management

**Comment by irfaan96** [comment]
What worked well: The allocation of tasks among the team members were fair and manageable and no conflicts among any team members.

What didn't work: The communication between other teams were not good eventually leading to our feature not being fully functional.

**Comment by jibai-kia** [comment]
In class, integration discussions were difficult to implement, causing teams to find alternatives that affected the final integration. Testing was lacking during implementation, but team dynamics were great with fair task allocation and no conflicts. However, communication issues with other teams led to our feature not being fully functional. There was a rush to integrate right before the client presentation, so improving time management will be a priority for the future.

**Comment by hengwej** [comment]
Overall, I think the project was quite well done. We had great team dynamics, we will always communicate and discuss the project. What could have done better was to have more communication between the teams whether on the data we needed for our feature or during integration. Another thing that we could have done better as a team was to do more testings on the program to ensure that the feature is working well and properly.
